In [2]:
import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

# 1. CSV 파일 불러오기
train = pd.read_csv("purchase_train.csv")
test = pd.read_csv("purchase_test.csv")

# 2. 데이터 기본 정보 확인
display('데이터 기본 정보 확인')
display(train.head())
display(train.tail())
display(train.shape)
display(train.info())

# 3. 기술통계 확인
display('기술통계 확인')
display(train.describe())
display(train.describe(include="object"))

# 4. 컬럼명 및 데이터 타입 확인
display('컬럼명 및 데이터 타입 확인')
display(train.columns)
display(train.dtypes)

# 5. 결측치 확인
display('결측치 확인')
display(train.isnull().sum())
display(train.isnull().sum().sum())

# 6. 결측치 비율 확인 (%)
display('결측치 비율 확인')
display((train.isnull().mean() * 100).round(2))

# 7. 중복 데이터 확인
display('중복 데이터 확인')
display(train.duplicated().sum())

# 8. 고유값 개수 확인
display('고유값 개수 확인')
display(train.nunique()) # 범주타입(purchase)만 확인해도 됨

# 9. 타깃 변수 분포 확인
# 타깃 컬럼명이 purchase라고 가정
display('타깃 변수 분포 확인')
display(train["purchase"].value_counts())
display(train["purchase"].value_counts(normalize=True).round(3))

'데이터 기본 정보 확인'

   age  income  visits purchase
0   22     220       2      아니오
1   25     250       3      아니오
2   28     280       4      아니오
3   35     350       5        예
4   40     400       6        예

    age  income  visits purchase
15   31     310       4      아니오
16   37     370       6        예
17   44     440       7        예
18   26     260       3      아니오
19   52     520       9        예

(20, 4)

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       20 non-null     int64
 1   income    20 non-null     int64
 2   visits    20 non-null     int64
 3   purchase  20 non-null     str
dtypes: int64(3), str(1)
memory usage: 772.0 bytes

None

'기술통계 확인'

             age      income     visits
count  20.000000   20.000000  20.000000
mean   36.550000  365.500000   5.400000
std    10.143575  101.435746   2.233713
min    22.000000  220.000000   2.000000
25%    27.750000  277.500000   3.750000
50%    36.000000  360.000000   5.500000
75%    44.250000  442.500000   7.000000
max    55.000000  550.000000   9.000000

C:\Users\user\AppData\Local\Temp\ipykernel_15548\746011190.py:28: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(train.describe(include="object"))

       purchase
count        20
unique        2
top           예
freq         12

'컬럼명 및 데이터 타입 확인'

Index(['age', 'income', 'visits', 'purchase'], dtype='str')

age         int64
income      int64
visits      int64
purchase      str
dtype: object

'결측치 확인'

age         0
income      0
visits      0
purchase    0
dtype: int64

np.int64(0)

'결측치 비율 확인'

age         0.0
income      0.0
visits      0.0
purchase    0.0
dtype: float64

'중복 데이터 확인'

np.int64(0)

'고유값 개수 확인'

age         20
income      20
visits       8
purchase     2
dtype: int64

'타깃 변수 분포 확인'

purchase
예      12
아니오     8
Name: count, dtype: int64

purchase
예      0.6
아니오    0.4
Name: proportion, dtype: float64